name: Laravel

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create temp directory
      run: mkdir -p /tmp/packages/arpanext/laravel-swagger-api
    - name: Move package source to temp directory
      run: mv -v ./* /tmp/packages/arpanext/laravel-swagger-api
    - name: test
      run: ls -la
    - name: Installa Laravel via Composer
      run: composer create-project laravel/laravel .
    - name: Move package to the current laravel project
      run: mv -v /tmp/packages ./
    - name: Install the package
      run: sed '/"require"/i "repositories":[{ "type":"path","url":"./packages/arpanext/laravel-swagger-api","options":{"symlink":true}}],' composer.json
    - name: composer
      run: composer dumpautoload
    - name: install
      run: composer require arpanext/laravel-swagger-api
    - name: php artisan vendor:publish --provider=Arpanext\\SwaggerApi\\App\\Providers\\AppServiceProvider
      run: php artisan vendor:publish --provider=Arpanext\\SwaggerApi\\App\\Providers\\AppServiceProvider
    - name: git clone https://github.com/zircote/swagger-php.git /tmp/swagger-php
      run: git clone https://github.com/zircote/swagger-php.git /tmp/swagger-php
    - name: mkdir -p app/Http/Controllers/Api
      run: mkdir -p app/Http/Controllers/Api
    - name: cp -r /tmp/swagger-php/Examples/petstore-3.0 ./app/Http/Controllers/Api/petstore-3.0
      run: cp -r /tmp/swagger-php/Examples/petstore-3.0 ./app/Http/Controllers/Api/petstore-3.0
    - name: vendor/bin/phpunit tests/
      run: vendor/bin/phpunit tests/


